module.exports = {
	extends: [
		'./index',
	].map(require.resolve),
	parserOptions: {
		ecmaFeatures: {
			jsx: true,
		},
	},
	plugins: [
		'react',
	],
	rules: {
		'react/no-children-prop': ['error'],
		'react/no-danger': ['error'],
		'react/no-danger-with-children': ['error'],
		'react/no-deprecated': ['error'],
		'react/no-did-mount-set-state': ['error'],
		'react/no-did-update-set-state': ['error'],
		'react/no-direct-mutation-state': ['error'],
		'react/no-find-dom-node': ['error'],
		'react/no-is-mounted': ['error'],
		'react/no-multi-comp': ['error'],
		'react/no-render-return-value': ['error'],
		'react/no-typos': ['error'],
		'react/no-unescaped-entities': ['error'],
		'react/no-unknown-property': ['error'],
		'react/no-unused-prop-types': ['error'],
		'react/prefer-stateless-function': ['error'],
		'react/react-in-jsx-scope': ['error'],
		'react/require-render-return': ['error'],
		'react/jsx-boolean-value': ['error', 'never'],
		'react/jsx-closing-bracket-location': ['error'],
		'react/jsx-equals-spacing': ['error', 'never'],
		'react/jsx-first-prop-new-line': ['error', 'multiline'],
		'react/jsx-indent': ['error', 4],
		'react/jsx-indent-props': ['error', 4],
		'react/jsx-key': ['error'],
		'react/jsx-no-comment-textnodes': ['error'],
		'react/jsx-no-duplicate-props': ['error'],
		'react/jsx-no-target-blank': ['error'],
		'react/jsx-no-undef': ['error'],
		'react/jsx-pascal-case': ['error'],
		'react/jsx-uses-react': ['error'],
		'react/jsx-uses-vars': ['error'],
		'react/jsx-wrap-multilines': ['error'],
	},
};
